FROM node:lts-buster as builder
WORKDIR /client
COPY ./client ./
RUN npm ci
RUN npm run build

FROM nginx:stable-alpine
COPY --from=builder /client/build /usr/share/nginx/html
COPY ./client/nginx.conf.prod /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD nginx -g "daemon off;"
